services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/nginx.prod.dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
      - php
      - assets

  php:
    build:
      context: .
      dockerfile: docker/php/php.prod.dockerfile

  assets:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: ["/bin/sh", "-c", "npm install && npm run build"]
